import json
import unittest
from datetime import datetime, timedelta, timezone
from urllib.parse import urlencode

from qa_agent.automation_lifecycle import (
    AutomationLifecycleService,
    AutomationStatus,
    InMemoryAutomationLifecycleRepository,
)
from qa_agent.execution_repository import InMemoryExecutionRepository
from qa_agent.models import (
    Execution,
    ExecutionStatus,
    PlanVersionOrigin,
    QATestPlan,
    QATestStep,
    TestCase as DomainTestCase,
    TestPlan as DomainTestPlan,
    TestPlanVersion as DomainTestPlanVersion,
    TestRun as DomainTestRun,
    TestStep as DomainTestStep,
)
from qa_agent.plan_store import InMemoryPlanStore
from qa_agent.reporting import RunReportGenerator
from qa_agent.run_history import InMemoryRunHistoryRepository, RunHistoryService, WorkflowType
from qa_agent.test_case_repository import InMemoryTestCaseRepository
from qa_agent.testplan_export import TestPlanExportService as DomainTestPlanExportService
from qa_agent.web import LocalWebApplication


class AutomationEditorTests(unittest.TestCase):
    def setUp(self) -> None:
        self.step = DomainTestStep(
            name="Fill registration email", description="Enter an email.",
            expected="The email is entered.", order=0,
        )
        self.case = DomainTestCase(
            name="Registration flow", description="Register a user.",
            base_url="https://example.test/register", steps=[self.step],
        )
        self.cases = InMemoryTestCaseRepository()
        self.cases.save(self.case)
        self.plans = InMemoryPlanStore()
        self.plan = DomainTestPlan(test_step_id=self.step.id, name=self.step.name)
        self.version_one = DomainTestPlanVersion(
            test_plan_id=self.plan.id,
            version=1,
            origin=PlanVersionOrigin.AI_GENERATED,
            qa_test_plan=QATestPlan(
                url="https://example.test/register",
                steps=[QATestStep(action="fill", parameters={"selector": "#email", "value": "old@example.test"})],
            ),
        )
        self.plans.save(self.step.id, self.version_one, test_plan=self.plan)
        self.lifecycle_repository = InMemoryAutomationLifecycleRepository()
        self.lifecycle = AutomationLifecycleService(self.lifecycle_repository, self.plans)
        self.history = RunHistoryService(
            InMemoryRunHistoryRepository(), InMemoryExecutionRepository(), self.plans
        )
        # Deliberately do not configure providers, authoring services, or an LLM router.
        self.app = LocalWebApplication(
            self.history,
            test_cases=self.cases,
            plan_store=self.plans,
            automation_lifecycle=self.lifecycle,
        )

    def tearDown(self) -> None:
        self.app.close()

    def save_form(self, *, expected_version="1", action="fill", **fields):
        values = {
            "expected_version": expected_version,
            "plan_url": "https://example.test/register",
            "action.0.type": action,
            **fields,
        }
        return self.app.handle(
            "POST",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/save",
            urlencode(values),
        )

    def test_editor_entry_current_plan_and_natural_provenance(self) -> None:
        case_html = self.app.handle("GET", f"/test-cases/{self.case.id}").body.decode()
        editor = self.app.handle("GET", f"/test-cases/{self.case.id}/automation/edit")
        body = editor.body.decode()

        self.assertIn("Edit Automation", case_html)
        self.assertEqual(editor.status, 200)
        self.assertIn("Current plan: <strong>v1</strong>", body)
        self.assertIn("Generated by AI", body)
        self.assertIn('name="action.0.param.selector"', body)
        self.assertIn("Version history", body)
        self.assertIn("v1 · Generated by AI · current", body)

    def test_save_creates_immutable_human_version_and_validation_gate_without_ai(self) -> None:
        self.assertEqual(
            self.lifecycle.mark_validation_completed(self.case, True),
            AutomationStatus.AUTOMATION_READY,
        )
        response = self.save_form(
            **{
                "action.0.param.selector": "#email-address",
                "action.0.param.value": "new@example.test",
            }
        )

        self.assertEqual(response.status, 303)
        current = self.plans.find(self.step.id)
        self.assertEqual(current.version, 2)
        self.assertEqual(current.origin, PlanVersionOrigin.HUMAN_EDITED)
        self.assertEqual(current.qa_test_plan.steps[0].parameters["selector"], "#email-address")
        self.assertEqual(self.plans.get_version(self.version_one.id), self.version_one)
        self.assertEqual(
            [item.version for item in self.plans.list_versions(self.step.id)], [2, 1]
        )
        self.assertEqual(self.lifecycle.status(self.case), AutomationStatus.NEEDS_VALIDATION)

        confirmation = self.app.handle(
            "GET", f"/test-cases/{self.case.id}/automation/edit?saved=1"
        ).body.decode()
        self.assertIn("Automation saved.", confirmation)
        self.assertIn("Review the current TestPlan", confirmation)
        self.assertIn("approve these saved versions for Validation", confirmation)
        self.assertNotIn("Run Validation", confirmation)
        self.assertIn("Edited locally", confirmation)
        self.app.handle("GET", f"/test-cases/{self.case.id}/automation/edit?saved=1")
        self.assertEqual(self.plans.find(self.step.id).version, 2)
        self.assertEqual(
            self.lifecycle.mark_validation_completed(self.case, passed=False),
            AutomationStatus.NEEDS_VALIDATION,
        )
        self.assertEqual(
            self.lifecycle.mark_validation_completed(self.case, passed=True),
            AutomationStatus.AUTOMATION_READY,
        )

    def test_add_delete_duplicate_reorder_and_action_type_form_shapes_save(self) -> None:
        response = self.app.handle(
            "POST",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/save",
            urlencode({
                "expected_version": "1",
                "plan_url": "https://example.test/register",
                "action.0.type": "navigate",
                "action.0.param.url": "https://example.test/start",
                "action.1.type": "fill",
                "action.1.param.selector": "#email",
                "action.1.param.value": "old@example.test",
                "action.2.type": "click",
                "action.2.param.selector": "#submit",
            }),
        )
        self.assertEqual(response.status, 303)
        saved = self.plans.find(self.step.id)
        self.assertEqual([step.action for step in saved.qa_test_plan.steps], ["navigate", "fill", "click"])

        # The form is the server contract used after the UI's duplicate/delete/move controls.
        response = self.app.handle(
            "POST",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/save",
            urlencode({
                "expected_version": "2",
                "plan_url": "https://example.test/register",
                "action.0.type": "assert_page_loaded",
                "action.1.type": "click",
                "action.1.param.selector": "#submit",
            }),
        )
        self.assertEqual(response.status, 303)
        self.assertEqual(
            [step.action for step in self.plans.find(self.step.id).qa_test_plan.steps],
            ["assert_page_loaded", "click"],
        )
        editor_js = self.app.handle("GET", "/assets/ui.js").body.decode()
        for control in ("data-action-add", "data-action-duplicate", "data-action-remove", "data-action-move"):
            self.assertIn(control, editor_js)
        self.assertIn("renderFields", editor_js)

    def test_invalid_required_field_preserves_input_and_does_not_mutate_lifecycle(self) -> None:
        self.lifecycle.mark_validation_completed(self.case, True)
        response = self.save_form(action="click")
        body = response.body.decode()

        self.assertEqual(response.status, 400)
        self.assertIn("Selector is required for this action.", body)
        self.assertIn('value="https://example.test/register"', body)
        self.assertEqual(self.plans.find(self.step.id), self.version_one)
        self.assertEqual(self.lifecycle.status(self.case), AutomationStatus.AUTOMATION_READY)

    def test_checkbox_state_actions_are_editable_and_create_human_versions(self) -> None:
        editor_js = self.app.handle("GET", "/assets/ui.js").body.decode()
        for action in ("check", "uncheck", "assert_unchecked"):
            self.assertIn(action, editor_js)

        unchecked = self.save_form(action="uncheck", **{"action.0.param.selector": "#terms"})
        self.assertEqual(unchecked.status, 303)
        second = self.plans.find(self.step.id)
        self.assertEqual(second.version, 2)
        self.assertEqual(second.origin, PlanVersionOrigin.HUMAN_EDITED)
        self.assertEqual(second.qa_test_plan.steps[0].action, "uncheck")

        verified = self.save_form(
            expected_version="2",
            action="assert_unchecked",
            **{"action.0.param.selector": "#terms"},
        )
        self.assertEqual(verified.status, 303)
        third = self.plans.find(self.step.id)
        self.assertEqual(third.version, 3)
        self.assertEqual(third.origin, PlanVersionOrigin.HUMAN_EDITED)
        self.assertEqual(third.qa_test_plan.steps[0].action, "assert_unchecked")
        self.assertEqual(self.plans.get_version(second.id), second)

    def test_unsupported_action_parameter_and_unsafe_urls_are_rejected(self) -> None:
        unsupported = self.save_form(
            **{
                "action.0.param.selector": "#submit",
                "action.0.param.script": "alert(1)",
            }
        )
        self.assertEqual(unsupported.status, 400)
        self.assertIn("not supported for the selected action", unsupported.body.decode())
        self.assertEqual(self.plans.find(self.step.id), self.version_one)

        credential_url = self.app.handle(
            "POST",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/save",
            urlencode({
                "expected_version": "1", "plan_url": "https://user:EDITOR_SECRET_SENTINEL@example.test/",
                "action.0.type": "assert_page_loaded",
            }),
        )
        self.assertEqual(credential_url.status, 400)
        self.assertIn("credentials", credential_url.body.decode())
        self.assertNotIn("EDITOR_SECRET_SENTINEL", credential_url.body.decode())

        script_url = self.app.handle(
            "POST",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/save",
            urlencode({
                "expected_version": "1", "plan_url": "https://example.test/",
                "action.0.type": "navigate", "action.0.param.url": "javascript:alert(1)",
            }),
        )
        self.assertEqual(script_url.status, 400)
        self.assertIn("valid HTTP or HTTPS URL", script_url.body.decode())
        self.assertEqual(self.plans.find(self.step.id), self.version_one)

    def test_stale_editor_conflict_and_read_only_old_version(self) -> None:
        first_save = self.save_form(
            **{
                "action.0.param.selector": "#first",
                "action.0.param.value": "one@example.test",
            }
        )
        self.assertEqual(first_save.status, 303)
        stale = self.save_form(
            **{
                "action.0.param.selector": "#stale",
                "action.0.param.value": "stale@example.test",
            }
        )
        self.assertEqual(stale.status, 409)
        self.assertIn("changed since you opened the editor", stale.body.decode())
        self.assertEqual(self.plans.find(self.step.id).version, 2)

        old = self.app.handle(
            "GET",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/versions/{self.version_one.id}",
        )
        old_html = old.body.decode()
        self.assertEqual(old.status, 200)
        self.assertIn("Read-only historical version", old_html)
        self.assertIn("old@example.test", old_html)
        self.assertNotIn('<form method="post"', old_html)

    def test_missing_step_can_be_created_manually_and_export_uses_current_version(self) -> None:
        second_step = DomainTestStep(
            name="Confirm welcome", description="Check the welcome panel.",
            expected="Welcome text appears.", order=1,
        )
        two_step_case = DomainTestCase(
            name="Two-step registration", description="Register and verify.",
            base_url="https://example.test/register", steps=[self.step, second_step],
        )
        self.cases.save(two_step_case)
        editor = self.app.handle("GET", f"/test-cases/{two_step_case.id}/automation/edit").body.decode()
        self.assertIn("Not automated. Create automation manually with supported actions.", editor)
        self.assertIn("Create", editor)

        response = self.app.handle(
            "POST",
            f"/test-cases/{two_step_case.id}/automation/steps/{second_step.id}/save",
            urlencode({
                "expected_version": "0", "plan_url": "https://example.test/register",
                "action.0.type": "assert_page_loaded",
            }),
        )
        self.assertEqual(response.status, 303)
        manual = self.plans.find(second_step.id)
        self.assertEqual(manual.version, 1)
        self.assertEqual(manual.origin, PlanVersionOrigin.HUMAN_EDITED)
        self.assertEqual(self.lifecycle.status(two_step_case), AutomationStatus.NEEDS_VALIDATION)

        latest = self.app.handle(
            "POST",
            f"/test-cases/{self.case.id}/automation/steps/{self.step.id}/save",
            urlencode({
                "expected_version": "1", "plan_url": "https://example.test/register",
                "action.0.type": "fill", "action.0.param.selector": "#email",
                "action.0.param.value": "export-current@example.test",
            }),
        )
        self.assertEqual(latest.status, 303)
        portable, _ = DomainTestPlanExportService(self.cases, self.plans).portable_json(self.case.id)
        exported = json.loads(portable)
        exported_value = exported["test_case"]["segments"][0]["steps"][0]["testplan_version"]["plan"]["steps"][0]["parameters"]["value"]
        self.assertEqual(exported_value, "export-current@example.test")

    def test_incomplete_human_plan_is_saved_but_shows_missing_coverage_and_stays_unready(self) -> None:
        verification_step = DomainTestStep(
            name="Verify an error message is displayed",
            description="Submit invalid registration data.",
            expected="An error message is displayed.",
            order=0,
        )
        case = DomainTestCase(
            name="Manual coverage review",
            description="A local registration validation check.",
            base_url="https://example.test/register",
            steps=[verification_step],
        )
        self.cases.save(case)

        response = self.app.handle(
            "POST",
            f"/test-cases/{case.id}/automation/steps/{verification_step.id}/save",
            urlencode({
                "expected_version": "0",
                "plan_url": "https://example.test/register",
                "action.0.type": "click",
                "action.0.param.selector": "#submit",
            }),
        )

        self.assertEqual(response.status, 303)
        self.assertEqual(self.plans.find(verification_step.id).origin, PlanVersionOrigin.HUMAN_EDITED)
        self.assertEqual(self.lifecycle.status(case), AutomationStatus.NEEDS_VALIDATION)
        self.assertEqual(
            self.lifecycle.mark_validation_completed(case, passed=True),
            AutomationStatus.NEEDS_VALIDATION,
        )
        editor = self.app.handle("GET", f"/test-cases/{case.id}/automation/edit").body.decode()
        test_plan = self.app.handle("GET", f"/test-cases/{case.id}/plans").body.decode()
        for page in (editor, test_plan):
            self.assertIn("Expected result coverage:", page)
            self.assertIn("Missing verification", page)
            self.assertIn("Automation does not verify the TestStep expected result.", page)

    def test_no_saved_plans_hides_editor_entry_but_existing_route_can_render_creation(self) -> None:
        empty_store = InMemoryPlanStore()
        app = LocalWebApplication(
            self.history, test_cases=self.cases, plan_store=empty_store,
        )
        try:
            detail = app.handle("GET", f"/test-cases/{self.case.id}").body.decode()
            editor = app.handle("GET", f"/test-cases/{self.case.id}/automation/edit").body.decode()
        finally:
            app.close()
        self.assertNotIn("Edit Automation", detail)
        self.assertIn("Not automated", editor)

    def test_run_history_keeps_the_original_version_id_and_provenance(self) -> None:
        execution = Execution(
            test_step_id=self.step.id,
            test_plan_version_id=self.version_one.id,
            status=ExecutionStatus.PASSED,
            started_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
            finished_at=datetime(2026, 1, 1, tzinfo=timezone.utc) + timedelta(seconds=1),
            actual_result="Passed",
        )
        run = DomainTestRun.from_test_case(self.case, [execution])
        record = self.history.record_completed_run(
            self.case, run, workflow_type=WorkflowType.REGRESSION,
            started_at=execution.started_at, finished_at=execution.finished_at,
        )
        self.save_form(
            **{
                "action.0.param.selector": "#after-run",
                "action.0.param.value": "later@example.test",
            }
        )
        detail = self.history.get_detail(run.id)

        self.assertEqual(detail.record.executions[0].test_plan_version_id, self.version_one.id)
        self.assertEqual(detail.record.executions[0].plan_version_number, 1)
        self.assertEqual(detail.record.executions[0].plan_version_origin, PlanVersionOrigin.AI_GENERATED)
        self.assertEqual(record.executions[0].test_plan_version_id, self.version_one.id)

        current = self.plans.find(self.step.id)
        edited_execution = Execution(
            test_step_id=self.step.id,
            test_plan_version_id=current.id,
            status=ExecutionStatus.PASSED,
            started_at=execution.started_at + timedelta(minutes=1),
            finished_at=execution.finished_at + timedelta(minutes=1),
            actual_result="Passed",
        )
        edited_run = DomainTestRun.from_test_case(self.case, [edited_execution])
        self.history.record_completed_run(
            self.case, edited_run, workflow_type=WorkflowType.VALIDATION,
            started_at=edited_execution.started_at, finished_at=edited_execution.finished_at,
        )
        edited_detail = self.history.get_detail(edited_run.id)
        report_generator = RunReportGenerator()
        report_html = report_generator.to_html(report_generator.generate_history(edited_detail))
        self.assertIn("v2 · Edited locally", report_html)


if __name__ == "__main__":
    unittest.main()
